### ISSUE TITLE
Questions about block.rs

### ISSUE THREAD

**Issue by Fractally** [voxelize/voxelize#2]
Hi there!

I am trying to understand the design decisions around [block.rs](https://github.com/shaoruu/voxelize/blob/master/server/world/block.rs) in the server code. I hope you don't mind answering my questions (I have yet to go through much of the code).

**Specific questions I have:**

- At first I thought you will package all the block data into a single u32 (because of the comment on line 5). This won't mean name, rotation, light levels, faces etc. also?
- Would rotation be limited to one axis only at a time? E.g. either rotate around X axis or Y axis. Never both?
- On line 33 you state there are 6 possible rotations. At first glance it almost feels like there should be only 3? Why 6?
- Why have both a `block id` and `block name`?
- What do you mean by `block stage`?

It will help a lot of you could explain the above to me. 😄 

Thanks!

**Comment by shaoruu** [comment]
Hi! Glad you're looking through the codebase!

Background knowledge about Voxelize:
- Each chunk consists of two n-dimensional arrays for data: voxels and lights. `voxels` contain details of each voxel position, including the (1) id, (2) rotation, (3) y-rotation, and (4) stage, and `lights` contain details about the light, including (1) red light, (2) green light, (3) blue light, (4) sunlight.

Here are the answers to your questions:
- As mentioned above, block data contains id, rotation, y-rotation, and stage.
- I split rotation into `rotation` and `y-rotation`. `rotation` would be where the "top of the block" is facing (position x,y,z), and `y-rotation` would be the rotation around the axis pointing towards the "top of the block". 
![IMG_0580](https://user-images.githubusercontent.com/35216312/166860572-7d2d9688-20af-4dca-9368-59611c8dd86a.jpg)
- Six rotation: positive x,y,z, and negative x,y,z
- I have both ID and Name because simply having IDs would be hard to identify which block it is, and only having names would be hard to pack into transferrable data.
- `block stage` is what I plan on using for sort of `metadata` for the block. Take example blocks like water in Minecraft, it seems to have a bunch of different forms, so I plan on using stages to differentiate between different forms.

If you got any more questions or ideas, feel free to ask!
