### ISSUE TITLE
Potential for worlds with different chunk-coordinate systems?

### ISSUE THREAD

**Issue by ac-z** [voxelize/voxelize#29]
Say I wanted to implement a game-mode where players can mine to indefinite depths...

To quote the documentation:
> Chunks are columns of blocks that make up an entire Voxelize world. By default, a chunk is 16x256x16 in dimension. A Voxelize world can be infinite because the world only generates the chunks around the clients, and as the client moves, more chunks are generated.
>
>Chunks have their own coordinate system, separate from the voxel coordinate system. Voxel coordinates are 3D in the x/y/z space, and chunk coordinates are 2D in the x/z plane. For example, if the chunk size is 16 blocks wide, the voxel (1, 1, 1) would reside in the chunk (0, 0), and the voxel (17, 1, 1) would reside in chunk (1, 0). If chunk has a max height of 256, a voxel coordinate such as (17, 256, 1) would be invalid since the valid y-coordinate range would be 0 - 255.

The existing implementation seems to be well-suited for worlds where players are expected to adventure outwards to an indefinite distance horizontally, but there isn't currently support for worlds that have the same principle but with infinite downwards generation instead.

I imagine this support could be introduced one of two ways:
1. Add an entirely different type of chunk-coordinate system for worlds to use, which uses 3D coordinates for chunks (which at this point could be any arbitrary shape instead of columns)
2. Add an option for a world to use an entirely different type of chunk, which consists of a Vec of Ndarray subchunks instead of a single Ndarray. This would allow each chunk-column to extend indefinitely downward without disturbing the current chunk-coordinate system.

Of course, servers with multiple worlds should be able to support both types of worlds simultaneously.

How much work would be needed to add something like this, back-end and front-end? I'm generally more familiar with Rust than js, but I can branch out if extensive work needs to be done.

**Comment by shaoruu** [comment]
That's interesting. 

When I started experimenting with the concept of Voxelize, 3D chunks were something that I tried but eventually didn't do. Primarily for this reason:

Voxel sunlight propagates top-to-bottom right now with the chunk system, but with 3D chunk, since there's no end downwards, there isn't a way to properly propagate the sunlight. The only solution I could think of is to assume sunlight would be zero after a certain y-level, but this solution feels very hacky, and isn't that sustainable with the custom stage-based terrain generation. In other words, if the developer decides to have words that have empty columns all throughout any x/z column, light would abruptly go from 15 to 0 pass that y level. Not sure if there are better ways of solving this. 

If we disregard the issue above, I could see these places requiring major refactoring in order for this to work:
- All voxel access would need a complete refactor, it's used throughout the app but in a 2D chunk fashion
- The entire chunk generation and meshing pipeline would need a LOT of refactor too. Right now the process goes: 1. Chunk is generated, 2. Each chunk waits for the neighbors to generate, 3. Once neighbors are generated, I mesh the chunk
    - This would mean to do 3D chunking, we'd have to wait not just the horizontal but also the vertical neighbors for the chunk to start meshing
    
Until we find a solution to the voxel sunlight issue, I'm not sure if 3D chunks are doable. Unless sunlight is turned off for 3D-chunk based worlds? That'd be pretty ugly imo

**Comment by ac-z** [comment]
Could a lot of that refactoring be skipped if we took the second route I proposed?
![image](https://github.com/voxelize/voxelize/assets/113668892/0ddf3352-8387-4206-8cb4-2d3302cd035d)
I imagine using an enum option to represent empty chunks would help with the sunlight issue, as it would be far easier to tell when a particular chunk column is empty.
I'd rather put work into an existing project than make my own engine, so if this still needs a significant amount of work, it may be worth it on my end.

**Comment by shaoruu** [comment]
This would be a great starting point, but how would you solve the sunlight propagation issue that I mentioned?

**Comment by ac-z** [comment]
> This would be a great starting point, but how would you solve the sunlight propagation issue that I mentioned?

Other than skipping empty chunks to improve iteration time, I don't have an idea that wouldn't introduce more work. 

If it's worth it to replace the lighting system with something a bit more fleshed out, you could have the server store light occlusion geometry separately from the chunked voxel storage. If you used an octree, casting rays downwards might be a lot faster.

**Comment by ac-z** [comment]
It's also worth noting that disabling sunlight for worlds with this kind of geometry could work just fine for many types of worlds (e.g. underground-only worlds which are filled with blocks from top to bottom)

Could be cool for a nether-like situation, or even deeper layers still.

Although, maybe changing the chunk system isn't actually necessary for this? What maximum chunk height would still be reasonable? At what point is optimizing taller worlds actually warranted? I'll experiment when I have the time.

**Comment by shaoruu** [comment]
To be fair, you can experiment with changing the chunk height in any world you're interested in through [this](https://github.com/voxelize/voxelize/blob/95c08756d8a32677acc2e2c48ff49d76b52ceeaa/server/world/config.rs#L30-L31). I do like the idea of using octrees for faster raycast, I haven't tried that yet.

Although modifying the max height = longer chunk generation times

**Comment by shaoruu** [comment]
@ac-z Let me know if you decided to move on with this idea! Meanwhile, I will close this issue for now.
